[build]
  command = "npm run build"
  publish = "dist/esg-app/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable Angular runtime plugin for client-side rendering
[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    enable_ssr = false 